platform :ios, '10.0'
use_frameworks!

target 'PhotoSearch' do
  pod 'SDWebImage' # Убедитесь, что версия не указана, если хотите использовать последнюю
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end